#!/bin/sh
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=4:mem=64gb
#PBS -N good238_38t_mcc
cd "$HOME/GitHub" || exit 1
PROGRAM="$HOME/revbayes/projects/cmake/build-mpi/rb-mpi"
module load tools/dev; module load tools/prod; module load OpenMPI; module load GCC/14.3.0
mpirun -np 1 ${PROGRAM} "amphora-phylogeny/mcc_only_good238_38_tuned.Rev" \
       > "amphora-phylogeny/output/mcc_logfile_good238_38_tuned.log" 2>&1
ls -la "amphora-phylogeny/output/simple_run_good238_38_tuned_mcc.tree" >> "amphora-phylogeny/output/mcc_logfile_good238_38_tuned.log" 2>&1
