#!/bin/sh
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=4:mem=64gb
#PBS -N g238_76t_mccpr
cd "$HOME/GitHub" || exit 1
PROGRAM="$HOME/revbayes/projects/cmake/build-mpi/rb-mpi"
module load tools/dev; module load tools/prod; module load OpenMPI; module load GCC/14.3.0
mpirun -np 1 ${PROGRAM} "amphora-phylogeny/mcc_only_good238_76_tuned_perrun.Rev" \
       > "amphora-phylogeny/output/mcc_logfile_good238_76_tuned_perrun.log" 2>&1
ls -la "amphora-phylogeny/output/simple_run_good238_76_tuned_mcc_perrun.tree" >> "amphora-phylogeny/output/mcc_logfile_good238_76_tuned_perrun.log" 2>&1
