#!/bin/sh
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=4:mem=96gb
#PBS -N v2_38_mccpr
cd "$HOME/GitHub" || exit 1
PROGRAM="$HOME/revbayes/projects/cmake/build-mpi/rb-mpi"
module load tools/dev; module load tools/prod; module load OpenMPI; module load GCC/14.3.0
mpirun -np 1 ${PROGRAM} "amphora-phylogeny/mcc_only_v2_38_perrun.Rev" \
       > "amphora-phylogeny/output/mcc_logfile_v2_38_perrun.log" 2>&1
ls -la "amphora-phylogeny/output/simple_run_v2_38_mcc_perrun.tree" >> "amphora-phylogeny/output/mcc_logfile_v2_38_perrun.log" 2>&1
